/**
 * REST API Endpoint Constants matching backend routes
 * @constant
 * @type {Object}
 */
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    CHANGE_PASSWORD: "/auth/change-password",
    PROFILE: "/auth/profile",
  },
  USERS: {
    BASE: "/users",
    BY_ID: (id) => `/users/${id}`,
    RESET_PASSWORD: "/users/reset-password",
  },
  ROLES: {
    BASE: "/roles",
    BY_ID: (id) => `/roles/${id}`,
  },
  CUSTOMERS: {
    BASE: "/customers",
    SEARCH: "/customers/search",
    STATUS: (id) => `/customers/${id}/status`,
    BY_ID: (id) => `/customers/${id}`,
  },
  PRODUCTS: {
    BASE: "/products",
    SEARCH: "/products/search",
    STATUS: (id) => `/products/${id}/status`,
    BY_ID: (id) => `/products/${id}`,
  },
  INVENTORY: {
    BASE: "/inventory",
    SEARCH: "/inventory/search",
    MOVEMENTS: "/inventory/movements",
    ADJUST: "/inventory/adjust",
    RESERVE: "/inventory/reserve",
    RELEASE: "/inventory/release",
    BY_ID: (id) => `/inventory/${id}`,
  },
  SUPPLIERS: {
    BASE: "/suppliers",
    SEARCH: "/suppliers/search",
    BY_ID: (id) => `/suppliers/${id}`,
  },
  PURCHASES: {
    BASE: "/purchases",
    SEARCH: "/purchases/search",
    STATUS: (id) => `/purchases/${id}/status`,
    RECEIVE: (id) => `/purchases/${id}/receive`,
    CANCEL: (id) => `/purchases/${id}/cancel`,
    BY_ID: (id) => `/purchases/${id}`,
  },
  ORDERS: {
    BASE: "/orders",
    SEARCH: "/orders/search",
    STATUS: (id) => `/orders/${id}/status`,
    BY_ID: (id) => `/orders/${id}`,
  },
  INVOICES: {
    BASE: "/invoices",
    SEARCH: "/invoices/search",
    STATUS: (id) => `/invoices/${id}/status`,
    BY_ID: (id) => `/invoices/${id}`,
  },
  PAYMENTS: {
    BASE: "/payments",
    SEARCH: "/payments/search",
    STATUS: (id) => `/payments/${id}/status`,
    BY_ID: (id) => `/payments/${id}`,
  },
  SETTINGS: {
    BASE: "/settings",
    TOGGLE: "/settings/toggle",
  },
  REPORTS: {
    DASHBOARD_SUMMARY: "/reports/dashboard-summary",
    SALES: "/reports/sales",
    PURCHASES: "/reports/purchases",
    INVENTORY: "/reports/inventory",
    CUSTOMERS: "/reports/customers",
    SUPPLIERS: "/reports/suppliers",
    PAYMENTS: "/reports/payments",
    OUTSTANDING: "/reports/outstanding",
    PRODUCTS: "/reports/products",
  },
  DASHBOARD: {
    OVERVIEW: "/dashboard/overview",
    KPIS: "/dashboard/kpis",
    CHARTS: "/dashboard/charts",
    ACTIVITY: "/dashboard/activity",
    ALERTS: "/dashboard/alerts",
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    TEMPLATES: "/notifications/templates",
    SEND: (id) => `/notifications/${id}/send`,
    RETRY: (id) => `/notifications/${id}/retry`,
    CANCEL: (id) => `/notifications/${id}/cancel`,
    PREFERENCES: "/notifications/preferences",
  },
  CUSTOMER_PORTAL: {
    LOGIN: "/customer-portal/auth/login",
    REFRESH: "/customer-portal/auth/refresh",
    ENABLE_PORTAL: "/customer-portal/auth/enable-portal",
    DASHBOARD: "/customer-portal/dashboard",
    ORDERS: "/customer-portal/orders",
    ORDER_DETAILS: (id) => `/customer-portal/orders/${id}`,
    REORDER: (id) => `/customer-portal/orders/${id}/reorder`,
    INVOICES: "/customer-portal/invoices",
    INVOICE_DETAILS: (id) => `/customer-portal/invoices/${id}`,
    PAYMENTS: "/customer-portal/payments",
    OUTSTANDING: "/customer-portal/outstanding",
    PROFILE: "/customer-portal/profile",
    NOTIFICATIONS: "/customer-portal/notifications",
    MARK_NOTIFICATION_READ: (id) => `/customer-portal/notifications/${id}/read`,
    PRODUCTS: "/customer-portal/products",
    PRODUCT_DETAILS: (id) => `/customer-portal/products/${id}`,
    CATEGORIES: "/customer-portal/categories",
    OFFERS: "/customer-portal/offers",
    DRAFTS: "/customer-portal/drafts",
    FAVORITES: "/customer-portal/favorites",
    REMOVE_FAVORITE: (productId) => `/customer-portal/favorites/${productId}`,
    SUPPORT: "/customer-portal/support",
  },
  EXPORT: {
    INVOICE_PDF: (id) => `/export/invoice/${id}/pdf`,
    PURCHASE_PDF: (id) => `/export/purchase/${id}/pdf`,
    PAYMENT_PDF: (id) => `/export/payment/${id}/pdf`,
    CHALLAN_PDF: (id) => `/export/challan/${id}/pdf`,
    REPORT_EXCEL: (reportName) => `/export/report/${reportName}/excel`,
    REPORT_CSV: (reportName) => `/export/report/${reportName}/csv`,
  },
  AUDIT: {
    BASE: "/audit",
    ACTIVITY: "/audit/activity",
    BY_ID: (id) => `/audit/${id}`,
    ENTITY_HISTORY: (entity, id) => `/audit/entity/${entity}/${id}`,
    USER_ACTIVITY: (userId) => `/audit/user/${userId}`,
    MODULE_ACTIVITY: (module) => `/audit/module/${module}`,
  },
  AUTOMATION: {
    RULES: "/automation/rules",
    RULE_BY_ID: (id) => `/automation/rules/${id}`,
    TOGGLE_RULE: (id) => `/automation/rules/${id}/toggle`,
    CLONE_RULE: (id) => `/automation/rules/${id}/clone`,
    RUN_RULE: (id) => `/automation/rules/${id}/run`,
    EXECUTIONS: "/automation/executions",
    EXECUTION_BY_ID: (id) => `/automation/executions/${id}`,
    RETRY_EXECUTION: (id) => `/automation/executions/${id}/retry`,
    STATS: "/automation/stats",
    HEALTH: "/automation/health",
    SCHEDULER: "/automation/scheduler",
    SCHEDULER_PAUSE: "/automation/scheduler/pause",
    SCHEDULER_RESUME: "/automation/scheduler/resume",
  },
};
