/**
 * Global Route Constants for B2B ERP Router
 * @constant
 * @type {Object}
 */
export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  CUSTOMERS: "/customers",
  CUSTOMER_DETAILS: "/customers/:id",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: "/products/:id",
  ORDERS: "/orders",
  ORDER_DETAILS: "/orders/:id",
  BILLING: "/billing",
  INVOICE_DETAILS: "/billing/:id",
  PAYMENTS: "/payments",
  PAYMENT_DETAILS: "/payments/:id",
  REPORTS: "/reports",
  SETTINGS: "/settings",
  CUSTOMER_ORDERING: "/customer-ordering",
  INVENTORY: "/inventory",
  INVENTORY_DETAILS: "/inventory/:id",
  SUPPLIERS: "/suppliers",
  SUPPLIER_DETAILS: "/suppliers/:id",
  PURCHASES: "/purchases",
  PURCHASE_DETAILS: "/purchases/:id",
  USERS: "/users",
  ROLES: "/roles",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/change-password",
  NOTIFICATIONS: "/notifications",
  AUDIT_LOGS: "/audit",
  AUTOMATION: "/automation",
  BUSINESS_INTELLIGENCE: "/business-intelligence",
  COMMUNICATION: "/communication",
  DATA_PLATFORM: "/data-platform",
  IDENTITY: "/identity",
  OBSERVABILITY: "/observability",
  FINANCE: "/finance",
  SUPPLY_CHAIN: "/supply-chain",
  // Customer Self-Service Portal
  CUSTOMER_LOGIN: "/portal/login",
  CUSTOMER_DASHBOARD: "/portal/dashboard",
  CUSTOMER_ORDERS: "/portal/orders",
  CUSTOMER_ORDER_DETAILS: "/portal/orders/:id",
  CUSTOMER_INVOICES: "/portal/invoices",
  CUSTOMER_INVOICE_DETAILS: "/portal/invoices/:id",
  CUSTOMER_PAYMENTS: "/portal/payments",
  CUSTOMER_PROFILE: "/portal/profile",
  CUSTOMER_NOTIFICATIONS: "/portal/notifications",
  CUSTOMER_HELP: "/portal/help",
  // Phase-2: Transactional Portal
  CUSTOMER_PRODUCTS: "/portal/products",
  CUSTOMER_PRODUCT_DETAILS: "/portal/products/:id",
  CUSTOMER_CART: "/portal/cart",
  CUSTOMER_CHECKOUT: "/portal/checkout",
  CUSTOMER_DRAFTS: "/portal/drafts",
  CUSTOMER_FAVORITES: "/portal/favorites",
  CUSTOMER_OFFERS: "/portal/offers",
  CUSTOMER_SUPPORT: "/portal/support",
};
