/**
 * Standardized ERP Event Registry
 */
const EVENTS = {
  // Order Events
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_UPDATED: "ORDER_UPDATED",
  ORDER_CANCELLED: "ORDER_CANCELLED",

  // Billing & Payment Events
  INVOICE_GENERATED: "INVOICE_GENERATED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_OVERDUE: "PAYMENT_OVERDUE",

  // Inventory & Product Events
  PRODUCT_CREATED: "PRODUCT_CREATED",
  INVENTORY_UPDATED: "INVENTORY_UPDATED",
  LOW_STOCK: "LOW_STOCK",

  // Purchase & Supplier Events
  PURCHASE_CREATED: "PURCHASE_CREATED",
  PURCHASE_APPROVED: "PURCHASE_APPROVED",
  SUPPLIER_ADDED: "SUPPLIER_ADDED",

  // Customer & Account Events
  CUSTOMER_REGISTERED: "CUSTOMER_REGISTERED",

  // Security & Identity Events
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  ROLE_UPDATED: "ROLE_UPDATED",

  // System & Infrastructure Events
  BACKUP_COMPLETED: "BACKUP_COMPLETED",
  AUTOMATION_FAILED: "AUTOMATION_FAILED",
  AI_ANALYSIS_COMPLETED: "AI_ANALYSIS_COMPLETED",
  REPORT_GENERATED: "REPORT_GENERATED",
  EXPORT_COMPLETED: "EXPORT_COMPLETED",
  SYSTEM_ERROR: "SYSTEM_ERROR",
};

module.exports = {
  EVENTS,
};
