export const ROUTES = {
  QR_LANDING: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: "/products/:id",
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDERS: "/orders",
  ORDER_DETAILS: "/orders/:id",
  INVOICES: "/invoices",
  INVOICE_DETAILS: "/invoices/:id",
  PAYMENTS: "/payments",
  OFFERS: "/offers",
  FAVORITES: "/favorites",
  NOTIFICATIONS: "/notifications",
  SUPPORT: "/support",
  PROFILE: "/profile",
  SETTINGS: "/settings",
};
